extern int price_cdo    __PARAMS((const int     *n_comp, 
                                  const double      *nominal,
                                  const int     n_dates,
                                  const double      *dates,
                                  const int     n_tranches,
                                  const double      *tr,
                                  const double      *intensity,
                                  const int     n_rates,
                                  const double      *x_rates,
                                  const double      *y_rates,
                                  const int     *t_recovery,
                                  const double      *recovery,
                                  const int     *t_copula,
                                  const double      *p_copula,
                                  const int     *t_method,
                                  const int     *p_method,
                                  double        *price,
                                  double        *def_leg,
                                  double        *pay_leg));
