// generated by builder.sce: Please do not edit this file
// ------------------------------------------------------
libsci_cdo_path=get_file_path('loader.sce');
link(libsci_cdo_path+'/../src/.libs/libcdo.so');
link(libsci_cdo_path+'/../demo/.libs/libdemo.so');
functions=[ 'price_cdo';
];
addinter(libsci_cdo_path+'/libsci_cdo.so','libsci_cdo',functions);
