/*---------------------------------------------------------------------------*/
/*----------Extended Libor Market Models with stochastic Volatility----------*/
/*---------------------------------------------------------------------------*/
/*----------------------Audrey Drif, Premia 2006-----------------------------*/
/*---------------------------------------------------------------------------*/


#include <iostream>
#include <cmath>
#include <complex>
#include <cstdlib>
#include <fstream>
#include "LMM-ANDERSEN-IMPLIEDVOLATILITY-CAPS.h"
using namespace std;
typedef complex<double> dcomplex;

int main()
{
  int  m,n;
  double res,T;
  double X,eps;
  double lambda,alpha;
  dcomplex *w;
  w=new dcomplex[101]; 
  Varphi1 *Var1;
  Varphi2 *Var;
  Sigma0 *Sig0;
  Sigma1 *Sig1;
  Volconst *Vol;
  C1 *cc1;
  Sigma10 *Sig10;
  Sigma21 *Sig21;
  L12K *l;
  L120 *l0;
  Dsigma1 *Dsig1;
  Dsigma2 *Dsig2;
  Alpha0 *a0;
  Alpha1 *a1;
  C2 *cc2;
  Volsto1 *Vols1;
  L22K *ll;
  L220 *ll0;
  L23K *lll;
  L230 *lll0;
  Dsigma3 *Dsig3;
  Dsigma4 *Dsig4;
  Sigma20 *Sig20;
  Sigma30 *Sig30;
  Sigma31 *Sig31;
  Sigma41 *Sig41;
  Beta0 *bet0;
  Beta1 *bet1;
  Beta2 *bet2; 
  C3 *cc3;
  C4 *cc4;
  Volsto2 *Vols2;
  Volsto3 *Vols3;
  Caplet *c;
  Caplet0 *c0;
  bondprice* bb;
  bb=new bondprice();
   cout<<"\n";
  cout<<"Pricing Caplet using LMM Stochastic Volatility models\n";
  cout<<"\n";
  cout<<"(0) The volatility constant is assumed constant at V=1:\n";
  cout<<"(1) Stochastic volatility and expansion O2 with K=1, alpha=1:\n";
  cout<<"(2) Stochastic volatility and expansion O4 with K=1, alpha=1 Lambda=1:\n";
  cout<<"(3) Stochastic volatility and expansion O4 with K=0.5, alpha=1, Lambda=0:\n";
  cout<<"(4) Stochastic volatility and expansion O2 with K=1, 0<alpha<1:\n";
  cout<<"(5) Stochastic volatility and expansion O4 with K=1, 0<alpha<1, Lambda=1:\n";
  cout<<"(6) Stochastic volatility and expansion O4 with K=0, alpha=1, Lambda=1:\n";
  cout<<"(7) Stochastic volatility and expansion O2 with K=0, alpha=1 6:\n";
  cin>>m;

  switch(m)
    {
    case 0://stochastic volatility factor was set to 1
      cout<<"enter the strike X :";
      cin>>X;
      cout<<"enter the Implied Skew volatility lambda>0(example 0.06) value :";
      cin>>lambda;
      cout<<"enter the alpha value(>0 and <1) example 0.6 :";
      cin>>alpha;
      Var1=new Varphi1();
      Sig0=new Sigma0(Var1);
      Sig1=new Sigma1(Var1,Sig0);
      Vol=new Volconst(Sig0,Sig1);
      c0=new Caplet0(X,bb,Vol);
      res=c0->caplet0(lambda,alpha);
      cout<<"The price is :";
      cout<<res<<endl;
      break;
    case 1://Expansion O2 with K=1, alpha=1, lamb=0.06
      cout<<"enter the strike X :";
      cin>>X; 
      cout<<"enter the varepsilon value :";
      cin>>eps;
      cout<<"enter the Implied Skew volatility lambda>0(example 0.2) value :";
      cin>>lambda;
      Var=new Varphi2();
      Sig0=new Sigma0(Var);
      Sig1=new Sigma1(Var,Sig0);
      Vol=new Volconst(Sig0,Sig1);
      cc1=new C1();
      l=new L12K();
      Dsig1=new Dsigma1(Sig0,Sig1);
      Dsig2=new Dsigma2(Sig0,Sig1);
      Sig10=new Sigma10(Vol,Dsig1);
      Sig21=new Sigma21(Dsig1,Dsig2);
      a0=new Alpha0(Vol,l,Sig10,Sig21);
      a1=new Alpha1(Vol,l,Sig10);
      cc2=new C2(cc1,a0,a1,eps);
      Vols1=new Volsto1(cc2,Sig0,Sig1);
      c=new Caplet(X,bb,Vols1);
      res=c->caplet(lambda,1.,1.);
      cout<<"The price is :";
      cout<<res<<endl;
      break;
    case 2://Expansion O4 with K=1, alpha=1, lamb=0.2, Lambda=1 
      cout<<"enter the strike X :";
      cin>>X; 
      cout<<"enter the varepsilon value(example 1.5) :";
      cin>>eps;
      cout<<"enter the Implied Skew volatility lambda>0(example 0.2) value :";
      cin>>lambda;
      Var=new Varphi2();
      Sig0=new Sigma0(Var);
      Sig1=new Sigma1(Var,Sig0);
      Vol=new Volconst(Sig0,Sig1);
      cc1=new C1();
      l=new L12K();
      Dsig3=new Dsigma3(Sig0,Sig1);
      Dsig4=new Dsigma4(Sig0,Sig1);
      ll=new L22K();
      lll=new L23K();
      Dsig1=new Dsigma1(Sig0,Sig1);
      Dsig2=new Dsigma2(Sig0,Sig1);
      Sig10=new Sigma10(Vol,Dsig1);
      Sig21=new Sigma21(Dsig1,Dsig2);
      a0=new Alpha0(Vol,l,Sig10,Sig21);
      a1=new Alpha1(Vol,l,Sig10);
      Sig20=new Sigma20(Vol,Dsig2);
      Sig30=new Sigma30(Vol,Dsig3);
      Sig31=new Sigma31(Dsig1,Dsig3);
      Sig41=new Sigma41(Dsig1,Dsig4);
      bet0=new Beta0(Vol,l,ll,lll,Sig10,Sig20,Sig21,Sig30,Sig31,Sig41);
      bet1=new Beta1(Vol,l,ll,lll,Sig10,Sig20,Sig21,Sig30,Sig31);
      bet2=new Beta2(Vol,l,lll,Sig10,Sig20);
      cc3=new C3(cc1,a0,a1,bet0,bet1,bet2,eps);
      Vols2=new Volsto2(cc3,Sig0,Sig1);
      c=new Caplet(X,bb,Vols2);
      res=c->caplet(lambda,1.,1.);
      cout<<"The price is :";
      cout<<res<<endl;
      break;
    case 3://Expansion O4 with alpha=1, lamb=0.2, Lambda=0, K=0.5
      cout<<"enter the strike X :";
      cin>>X; 
      cout<<"enter the varepsilon value(example 1.5) :";
      cin>>eps;
      cout<<"enter the Implied Skew volatility lambda>0(example 0.2) value :";
      cin>>lambda;
      Var=new Varphi2();
      Sig0=new Sigma0(Var);
      Sig1=new Sigma1(Var,Sig0);
      Vol=new Volconst(Sig0,Sig1);
      cc1=new C1();
      l=new L12K();
      Dsig3=new Dsigma3(Sig0,Sig1);
      Dsig4=new Dsigma4(Sig0,Sig1);
      ll=new L22K();
      lll=new L23K();
      Dsig1=new Dsigma1(Sig0,Sig1);
      Dsig2=new Dsigma2(Sig0,Sig1);
      Sig10=new Sigma10(Vol,Dsig1);
      Sig21=new Sigma21(Dsig1,Dsig2);
      a0=new Alpha0(Vol,l,Sig10,Sig21);
      a1=new Alpha1(Vol,l,Sig10);
      Sig20=new Sigma20(Vol,Dsig2);
      Sig30=new Sigma30(Vol,Dsig3);
      Sig31=new Sigma31(Dsig1,Dsig3);
      Sig41=new Sigma41(Dsig1,Dsig4);
      bet0=new Beta0(Vol,l,ll,lll,Sig10,Sig20,Sig21,Sig30,Sig31,Sig41);
      bet1=new Beta1(Vol,l,ll,lll,Sig10,Sig20,Sig21,Sig30,Sig31);
      bet2=new Beta2(Vol,l,lll,Sig10,Sig20);
      cc4=new C4(cc1,a0,a1,bet0,bet1,bet2,eps);
      Vols3=new Volsto3(cc4,Sig0,Sig1);
      c=new Caplet(X,bb,Vols3);
      res=c->caplet(lambda,1.,0.5);
      cout<<"The price is :";
      cout<<res<<endl;
      break; 
    case 4://expansion O2 with alpha=0.6, lamb=0.0649, K=1  
      cout<<"enter the strike X :";
      cin>>X; 
      cout<<"enter the varepsilon value(example 1.5) :";
      cin>>eps;
      cout<<"enter the Implied Skew volatility lambda>0(example 0.0649) value :";
      cin>>lambda;
      cout<<"enter the alpha value (>0 and <1) example 0.6 :";
      cin>>alpha;
      Var1=new Varphi1();
      Sig0=new Sigma0(Var1);
      Sig1=new Sigma1(Var1,Sig0);
      Vol=new Volconst(Sig0,Sig1);
      cc1=new C1();
      l=new L12K();
      Dsig1=new Dsigma1(Sig0,Sig1);
      Dsig2=new Dsigma2(Sig0,Sig1);
      Sig10=new Sigma10(Vol,Dsig1);
      Sig21=new Sigma21(Dsig1,Dsig2);
      a0=new Alpha0(Vol,l,Sig10,Sig21);
      a1=new Alpha1(Vol,l,Sig10);
      cc2=new C2(cc1,a0,a1,eps);
      Vols1=new Volsto1(cc2,Sig0,Sig1);
      c=new Caplet(X,bb,Vols1);
      res=c->caplet(lambda,alpha,1.);
      cout<<"The price is :";
      cout<<res<<endl;
      break;
    case 5://expansion O4 with varphi(x)=x^0.6 lamb=0.0649 K=1, Lambda=1 
      cout<<"enter the strike X :";
      cin>>X; 
      cout<<"enter the varepsilon value(example 1.5) :";
      cin>>eps;
      cout<<"enter the Implied Skew volatility lambda>0(example 0.0649) value :";
      cin>>lambda;
      cout<<"enter the alpha value (>0 and <1) example 0.6 :";
      cin>>alpha;
      Var1=new Varphi1();
      Sig0=new Sigma0(Var1);
      Sig1=new Sigma1(Var1,Sig0);
      Vol=new Volconst(Sig0,Sig1);
      cc1=new C1();
      l=new L12K();
      Dsig3=new Dsigma3(Sig0,Sig1);
      Dsig4=new Dsigma4(Sig0,Sig1);
      ll=new L22K();
      lll=new L23K();
      Dsig1=new Dsigma1(Sig0,Sig1);
      Dsig2=new Dsigma2(Sig0,Sig1);
      Sig10=new Sigma10(Vol,Dsig1);
      Sig21=new Sigma21(Dsig1,Dsig2);
      a0=new Alpha0(Vol,l,Sig10,Sig21);
      a1=new Alpha1(Vol,l,Sig10);
      Sig20=new Sigma20(Vol,Dsig2);
      Sig30=new Sigma30(Vol,Dsig3);
      Sig31=new Sigma31(Dsig1,Dsig3);
      Sig41=new Sigma41(Dsig1,Dsig4);
      bet0=new Beta0(Vol,l,ll,lll,Sig10,Sig20,Sig21,Sig30,Sig31,Sig41);
      bet1=new Beta1(Vol,l,ll,lll,Sig10,Sig20,Sig21,Sig30,Sig31);
      bet2=new Beta2(Vol,l,lll,Sig10,Sig20);
      cc3=new C3(cc1,a0,a1,bet0,bet1,bet2,eps);
      Vols2=new Volsto2(cc3,Sig0,Sig1);
      c=new Caplet(X,bb,Vols2);
      res=c->caplet(lambda,alpha,1.);
      cout<<"The price is :";
      cout<<res<<endl;
      break;
    case 6://Expansion O4 with K=0, alpha=1, lamb=0.2, Lambda=1
      cout<<"enter the strike X :";
      cin>>X; 
      cout<<"enter the varepsilon value(example 1.5) :";
      cin>>eps;
      cout<<"enter the lambda>0 value example 0.2:";
      cin>>lambda;
      Var=new Varphi2();
      Sig0=new Sigma0(Var);
      Sig1=new Sigma1(Var,Sig0);
      Vol=new Volconst(Sig0,Sig1);
      cc1=new C1();
      l0=new L120();
      Dsig3=new Dsigma3(Sig0,Sig1);
      Dsig4=new Dsigma4(Sig0,Sig1);
      ll0=new L220();
      lll0=new L230();
      Dsig1=new Dsigma1(Sig0,Sig1);
      Dsig2=new Dsigma2(Sig0,Sig1);
      Sig10=new Sigma10(Vol,Dsig1);
      Sig21=new Sigma21(Dsig1,Dsig2);
      a0=new Alpha0(Vol,l0,Sig10,Sig21);
      a1=new Alpha1(Vol,l0,Sig10);
      Sig20=new Sigma20(Vol,Dsig2);
      Sig30=new Sigma30(Vol,Dsig3);
      Sig31=new Sigma31(Dsig1,Dsig3);
      Sig41=new Sigma41(Dsig1,Dsig4);
      bet0=new Beta0(Vol,l0,ll0,lll0,Sig10,Sig20,Sig21,Sig30,Sig31,Sig41);
      bet1=new Beta1(Vol,l0,ll0,lll0,Sig10,Sig20,Sig21,Sig30,Sig31);
      bet2=new Beta2(Vol,l0,lll0,Sig10,Sig20);
      cc3=new C3(cc1,a0,a1,bet0,bet1,bet2,eps);
      Vols2=new Volsto2(cc3,Sig0,Sig1);
      c=new Caplet(X,bb,Vols2);
      res=c->caplet(lambda,1.,0.);
      cout<<"The price is :";
      cout<<res<<endl;
      break;
    case 7://Expansion O2 with  K=0, alpha=1, lamb=0.2
      cout<<"enter the strike X :";
      cin>>X; 
      cout<<"enter the varepsilon value(example 1.5) :";
      cin>>eps;
      cout<<"enter the lambda>0 value example 0.2:";
      cin>>lambda;
      Var=new Varphi2();
      Sig0=new Sigma0(Var);
      Sig1=new Sigma1(Var,Sig0);
      Vol=new Volconst(Sig0,Sig1);
      cc1=new C1();
      l0=new L120();
      Dsig1=new Dsigma1(Sig0,Sig1);
      Dsig2=new Dsigma2(Sig0,Sig1);
      Sig10=new Sigma10(Vol,Dsig1);
      Sig21=new Sigma21(Dsig1,Dsig2);
      a0=new Alpha0(Vol,l0,Sig10,Sig21);
      a1=new Alpha1(Vol,l0,Sig10);
      cc2=new C2(cc1,a0,a1,eps);
      Vols1=new Volsto1(cc2,Sig0,Sig1);
      c=new Caplet(X,bb,Vols1);
      res=c->caplet(lambda,1.,0.);
      cout<<"The price is :";
      cout<<res<<endl;
    }
}

