// generated by builder.sce: Please do not edit this file
// ------------------------------------------------------
libmanu_path=get_file_path('loader.sce');
functions=[ 'implied_volatility';
];
addinter(libmanu_path+'/libmanu.so','libmanu',functions);
