// generated by builder.sce: Please do not edit this file
// ------------------------------------------------------
libcalib_path=get_file_path('loader.sce');
functions=[ 'calib_ave_scilab';
];
addinter(libcalib_path+'/libcalib.so','libcalib',functions);
