/* do not edit : generated by ilib_ */
#include "nsp/machine.h"
#include "nsp/interf.h"


extern function nsp_premia_cdo;

static OpWrapTab libnsp_cdo_func[] = {
  {"price_cdo", nsp_premia_cdo,NULL},
  {(char *) 0, NULL, NULL},
};
int libnsp_cdo_Interf (int i, Stack stack, int rhs, int opt, int lhs)
{
  if ( libnsp_cdo_func[i].wrapper == NULL)
     return (*(libnsp_cdo_func[i].fonc)) (stack, rhs, opt, lhs);
  else 
     return (*(libnsp_cdo_func[i].wrapper)) (stack, rhs, opt, lhs,libnsp_cdo_func[i].fonc);
}
void libnsp_cdo_Interf_Info (int i, char **fname, function (**f))
{
 *fname = libnsp_cdo_func[i].name;
 *f = libnsp_cdo_func[i].fonc;
}
