// generated by builder.sce: Please do not edit this file
// ------------------------------------------------------
libnsp_cdo_path="./" // get_file_path('loader.sce');
link(libnsp_cdo_path+'/../src/.libs/libcdo.so');
link(libnsp_cdo_path+'/../demo/.libs/libdemo.so');
addinter(libnsp_cdo_path+'/libnsp_cdo.so','libnsp_cdo');
