/* do not edit : generated by ilib_ */
#include "nsp/machine.h"
#include "nsp/interf.h"


extern function int_premiamodel_create;
extern function int_premiamodel_init;
extern function int_premia_get_models;
extern function int_premia_get_family;
extern function int_premia_get_families;
extern function int_premia_get_methods;
extern function int_premia_get_assets;
extern function int_serial_test_unserialize;

static OpWrapTab libpremiamodel_func[] = {
  {"premia_create", int_premiamodel_create,NULL},
  {"premia_init", int_premiamodel_init,NULL},
  {"premia_get_models", int_premia_get_models,NULL},
  {"premia_get_family", int_premia_get_family,NULL},
  {"premia_get_families", int_premia_get_families,NULL},
  {"premia_get_methods", int_premia_get_methods,NULL},
  {"premia_get_assets", int_premia_get_assets,NULL},
  {"test_unserialize", int_serial_test_unserialize,NULL},
  {(char *) 0, NULL, NULL},
};
int libpremiamodel_Interf (int i, Stack stack, int rhs, int opt, int lhs)
{
  if ( libpremiamodel_func[i].wrapper == NULL)
     return (*(libpremiamodel_func[i].fonc)) (stack, rhs, opt, lhs);
  else 
     return (*(libpremiamodel_func[i].wrapper)) (stack, rhs, opt, lhs,libpremiamodel_func[i].fonc);
}
void libpremiamodel_Interf_Info (int i, char **fname, function (**f))
{
 *fname = libpremiamodel_func[i].name;
 *f = libpremiamodel_func[i].fonc;
}
