// generated by builder.sce: Please do not edit this file
// ------------------------------------------------------

libpremiamodel_path=file('join',['.','libpremiamodel.dylib']);
addinter(libpremiamodel_path,'libpremiamodel');
